### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by SanekSemenov** [SanekSemenov/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by SanekOlol** [comment]
A company is a group organized to create a product or service, and it is only as good as its people and how excited they are about creating. I do want to recognize a ton of super-talented people. I just happen to be the face of the companies.

**Comment by SanekSemenov** [comment]
That's great 👍
