### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by SanekSemenov** [SanekSemenov/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by SanekOlol** [comment]
EXPERIENCE

- 1983: Sold his first video game, Blastar.
- 1992: Went to University of Pennsylvania to Study Business and Physics. 
- 1995: Started Zip2, a Web Software Company.
- 1999: Sold Zip2 to Compaq for US$307 million
- 1999: Cofounded X.com, a financial service and payment company    
- 2000: X.com merged with Confinity to form PayPal, Musk married his first wife
- 2000: Musk got Fired from PayPal
- 2001: Went to Moscow to buy ICBMs to send payloads to Mars
- 2002: Got an idea to build affordable Rockets
- 2002: Founded SpaceX, a space exploration company
- 2004: Musk joined Tesla
- 2006: Musk's wife gave birth to triplets, Cofounded SolarCity and SpaceX Success
- 2007: Musk became the CEO of Tesla
- 2010: Donated a 25-kW Solar power system
- 2014: Announced Open-Sourcing Tesla Technology
- 2017: Purchased x.com domain from PayPal
- 2019: Traveled to China for the groundbreaking of Tesla's Shanghai Gigafactory
