### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by SanekSemenov** [SanekSemenov/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by SanekOlol** [comment]
EXPERIENCE

- 1983: Sold his first video game, Blastar.
- 1992: Went to University of Pennsylvania to Study Business and Physics. 
- 1995: Started Zip2, a Web Software Company.
- 1999: Sold Zip2 to Compaq for US$307 million
- 1999: Cofounded X.com, a financial service and payment company    
- 2000: X.com merged with Confinity to form PayPal, Musk married his first wife
- 2000: Musk got Fired from PayPal
- 2001: Went to Moscow to buy ICBMs to send payloads to Mars
- 2002: Got an idea to build affordable Rockets
- 2002: Founded SpaceX, a space exploration company
- 2004: Musk joined Tesla
- 2006: Musk's wife gave birth to triplets, Cofounded SolarCity and SpaceX Success
- 2007: Musk became the CEO of Tesla
- 2010: Donated a 25-kW Solar power system
- 2014: Announced Open-Sourcing Tesla Technology
- 2017: Purchased x.com domain from PayPal
- 2019: Traveled to China for the groundbreaking of Tesla's Shanghai Gigafactory
